apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../openshift

# Adds namespace to all resources.
namespace: kubernetes-operators

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: operator-lifecycle-manager
    app.kubernetes.io/name: loki-operator
    app.kubernetes.io/part-of: loki-operator
- pairs:
    app.kubernetes.io/instance: loki-operator-v0.6.1
    app.kubernetes.io/version: "0.6.1"

configMapGenerator:
- behavior: replace
  files:
  - controller_manager_config.yaml
  name: manager-config


images:
- name: controller
  newName: docker.io/grafana/loki-operator
  newTag: 0.6.1
